# Generated by Django 5.0.6 on 2025-08-28 10:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('genre', models.CharField(choices=[('RPG', 'RPG'), ('FPS', 'FPS'), ('MV', 'Metroidvania'), ('VN', 'Visual Novel'), ('PLAT', 'Platformer'), ('STR', 'Strategy'), ('ACT', 'Action-Adventure')], default='RPG', max_length=20)),
                ('ambiance', models.CharField(help_text='Ex: Cyberpunk, Dark Fantasy, Onirique...', max_length=200)),
                ('keywords', models.TextField(help_text='Mots-clés séparés par des virgules')),
                ('references', models.TextField(blank=True, null=True)),
                ('universe', models.TextField(blank=True, null=True)),
                ('story', models.TextField(blank=True, null=True)),
                ('locations', models.TextField(blank=True, null=True)),
                ('character_image_url', models.URLField(blank=True, null=True)),
                ('environment_image_url', models.URLField(blank=True, null=True)),
                ('is_public', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('role', models.CharField(max_length=120)),
                ('abilities', models.TextField()),
                ('motivation', models.TextField()),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characters', to='games.game')),
            ],
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='games.game')),
            ],
            options={
                'unique_together': {('user', 'game')},
            },
        ),
    ]
